Repository cloud-gov/cg-deploy-bosh, pull requests merged in 2020-04, with the labels that each got.

#416 added dedicated nessus type.
  cloud-config/base.yml
Labels: enhancement

#417 added dedicated type with ephemeral disk.
  cloud-config/base.yml
Labels: bug

#418 Adding in new ops file to limit max tasks to 200 from default 2000 to save disk space
  ci/pipeline.yml
  operations/max-tasks.yml
Labels: operations

#419 fix typo in ops add for pipeline
  ci/pipeline.yml
Labels: bug

#409 linear pipeline refactor
  ci/pipeline.yml
Labels: enhancement
